version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - ./backend/data:/app/data
    environment:
      - NODE_ENV=development
      - JWT_SECRET=gestion
      - SEED_DB=true    # Cambiar a "true" para insertar datos de ejemplo al iniciar
      - SEED_FORCE=false # Opcional: si true, forzaría re-seed (este ejemplo solo hace seed si tablas vacías)
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_INTERVAL=300
    depends_on:
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules:


